default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: giordanoalves
  password: password

# I'd move this to credentials if not a test
development:
  <<: *default
  database: mortgage_api_development

test:
  <<: *default
  database: mortgage_api_test
